workflows:
  flutter-mobile-staging:
    name: ShoPublish Mobile (Staging)
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: apps/mobile
    triggering:
      events:
        - push
      branches:
        - staging
      paths:
        - apps/mobile/**
        - codemagic.yaml
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build Android Debug APK
        script: |
          flutter build apk --debug
      - name: Build iOS Debug (Simulator)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/iphoneos/*.app

  flutter-mobile-prod:
    name: ShoPublish Mobile (Production)
    instance_type: mac_mini_m1
    max_build_duration: 120
    working_directory: apps/mobile
    triggering:
      events:
        - push
      branches:
        - main
      paths:
        - apps/mobile/**
        - codemagic.yaml
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Note: Secrets like signing keys and certificates should be added in Codemagic UI
      vars:
        APP_NAME: "ShoPublish"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Flutter test
        script: |
          flutter test
      - name: Build Android Release
        script: |
          # Ensure env vars for signing are set in Codemagic
          flutter build apk --release
          flutter build appbundle --release
      - name: Build iOS Release
        script: |
          # Code signing must be configured in Codemagic UI
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
